#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>
#define BOYUT 20

int adamlar[15] = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15};
int adamSayisi = 15;
int secimYap(){
    int dizi[1000] = {6,
                   11,
                   4,
                   3,
                   10,
                   16,
                   7,
                   10,
                   5,
                   6,
                   11,
                   3,
                   13,
                   16,
                   18,
                   3,
                   16,
                   13,
                   17,
                   6,
                   18,
                   9,
                   6,
                   5,
                   11,
                   11,
                   17,
                   11,
                   1,
                   9,
                   5,
                   13,
                   13,
                   3,
                   14,
                   13,
                   18,
                   19,
                   4,
                   5,
                   14,
                   10,
                   4,
                   12,
                   16,
                   14,
                   4,
                   18,
                   15,
                   16,
                   3,
                   16,
                   8,
                   10,
                   2,
                   13,
                   17,
                   8,
                   5,
                   10,
                   12,
                   4,
                   9,
                   3,
                   6,
                   8,
                   15,
                   12,
                   18,
                   8,
                   8,
                   11,
                   4,
                   11,
                   2,
                   8,
                   17,
                   15,
                   19,
                   14,
                   10,
                   4,
                   13,
                   12,
                   10,
                   1,
                   16,
                   19,
                   14,
                   1,
                   17,
                   4,
                   14,
                   2,
                   12,
                   7,
                   1,
                   10,
                   4,
                   18,
                   19,
                   15,
                   7,
                   17,
                   10,
                   18,
                   9,
                   12,
                   19,
                   14,
                   14,
                   3,
                   8,
                   9,
                   17,
                   16,
                   14,
                   14,
                   16,
                   15,
                   9,
                   10,
                   19,
                   16,
                   4,
                   14,
                   5,
                   1,
                   17,
                   2,
                   16,
                   5,
                   17,
                   7,
                   12,
                   8,
                   11,
                   16,
                   11,
                   18,
                   4,
                   3,
                   7,
                   16,
                   14,
                   18,
                   12,
                   10,
                   3,
                   14,
                   4,
                   14,
                   18,
                   13,
                   12,
                   11,
                   2,
                   3,
                   8,
                   5,
                   1,
                   13,
                   1,
                   5,
                   9,
                   19,
                   4,
                   15,
                   10,
                   17,
                   19,
                   17,
                   6,
                   3,
                   14,
                   2,
                   1,
                   15,
                   15,
                   1,
                   15,
                   18,
                   2,
                   14,
                   18,
                   19,
                   17,
                   18,
                   14,
                   9,
                   6,
                   6,
                   7,
                   16,
                   15,
                   11,
                   16,
                   8,
                   15,
                   17,
                   1,
                   18,
                   18,
                   6,
                   7,
                   18,
                   3,
                   8,
                   8,
                   11,
                   7,
                   4,
                   8,
                   13,
                   9,
                   8,
                   3,
                   4,
                   1,
                   19,
                   17,
                   14,
                   5,
                   17,
                   19,
                   7,
                   19,
                   17,
                   10,
                   14,
                   1,
                   13,
                   18,
                   9,
                   15,
                   3,
                   11,
                   10,
                   2,
                   14,
                   8,
                   10,
                   9,
                   1,
                   11,
                   5,
                   16,
                   17,
                   6,
                   9,
                   15,
                   2,
                   18,
                   12,
                   18,
                   11,
                   10,
                   10,
                   17,
                   9,
                   15,
                   17,
                   17,
                   5,
                   3,
                   13,
                   12,
                   8,
                   16,
                   9,
                   4,
                   9,
                   5,
                   15,
                   16,
                   15,
                   11,
                   16,
                   1,
                   9,
                   16,
                   3,
                   8,
                   3,
                   15,
                   2,
                   3,
                   10,
                   3,
                   16,
                   12,
                   1,
                   1,
                   16,
                   9,
                   1,
                   10,
                   12,
                   17,
                   18,
                   13,
                   1,
                   19,
                   2,
                   14,
                   13,
                   14,
                   17,
                   1,
                   6,
                   7,
                   5,
                   8,
                   2,
                   7,
                   14,
                   4,
                   2,
                   15,
                   1,
                   11,
                   14,
                   9,
                   8,
                   13,
                   5,
                   17,
                   19,
                   3,
                   6,
                   2,
                   7,
                   19,
                   10,
                   14,
                   7,
                   18,
                   14,
                   11,
                   10,
                   16,
                   14,
                   7,
                   9,
                   16,
                   3,
                   17,
                   13,
                   5,
                   16,
                   16,
                   2,
                   16,
                   17,
                   16,
                   18,
                   7,
                   16,
                   19,
                   13,
                   6,
                   15,
                   9,
                   9,
                   2,
                   14,
                   17,
                   11,
                   19,
                   1,
                   9,
                   11,
                   15,
                   11,
                   4,
                   5,
                   13,
                   2,
                   9,
                   19,
                   14,
                   19,
                   2,
                   1,
                   4,
                   16,
                   8,
                   11,
                   19,
                   12,
                   6,
                   9,
                   12,
                   3,
                   19,
                   2,
                   9,
                   17,
                   6,
                   5,
                   13,
                   8,
                   3,
                   19,
                   6,
                   10,
                   8,
                   2,
                   6,
                   5,
                   3,
                   13,
                   12,
                   14,
                   17,
                   4,
                   14,
                   5,
                   14,
                   18,
                   12,
                   6,
                   10,
                   1,
                   5,
                   17,
                   14,
                   17,
                   12,
                   9,
                   14,
                   6,
                   11,
                   1,
                   3,
                   17,
                   16,
                   17,
                   2,
                   16,
                   8,
                   4,
                   14,
                   18,
                   1,
                   9,
                   12,
                   6,
                   4,
                   14,
                   4,
                   8,
                   14,
                   19,
                   7,
                   8,
                   17,
                   5,
                   15,
                   3,
                   13,
                   14,
                   18,
                   14,
                   17,
                   8,
                   15,
                   8,
                   9,
                   2,
                   14,
                   11,
                   15,
                   17,
                   6,
                   9,
                   9,
                   17,
                   7,
                   7,
                   16,
                   13,
                   9,
                   11,
                   19,
                   5,
                   15,
                   2,
                   11,
                   14,
                   16,
                   7,
                   17,
                   5,
                   19,
                   14,
                   5,
                   1,
                   13,
                   15,
                   1,
                   18,
                   17,
                   11,
                   15,
                   1,
                   17,
                   1,
                   17,
                   9,
                   2,
                   12,
                   2,
                   10,
                   11,
                   14,
                   7,
                   10,
                   5,
                   13,
                   19,
                   16,
                   11,
                   17,
                   17,
                   15,
                   18,
                   14,
                   3,
                   9,
                   19,
                   19,
                   8,
                   5,
                   6,
                   18,
                   6,
                   15,
                   2,
                   8,
                   19,
                   13,
                   7,
                   16,
                   7,
                   8,
                   16,
                   3,
                   14,
                   19,
                   10,
                   7,
                   9,
                   1,
                   8,
                   10,
                   8,
                   15,
                   4,
                   1,
                   17,
                   3,
                   6,
                   12,
                   15,
                   10,
                   18,
                   5,
                   9,
                   13,
                   16,
                   15,
                   2,
                   7,
                   18,
                   4,
                   2,
                   1,
                   10,
                   13,
                   14,
                   5,
                   16,
                   9,
                   10,
                   5,
                   3,
                   9,
                   17,
                   13,
                   9,
                   10,
                   8,
                   13,
                   12,
                   14,
                   5,
                   18,
                   3,
                   11,
                   1,
                   6,
                   2,
                   16,
                   11,
                   1,
                   16,
                   13,
                   11,
                   5,
                   19,
                   5,
                   19,
                   19,
                   6,
                   6,
                   16,
                   9,
                   8,
                   16,
                   11,
                   7,
                   3,
                   13,
                   4,
                   13,
                   8,
                   16,
                   2,
                   12,
                   8,
                   13,
                   13,
                   10,
                   1,
                   2,
                   8,
                   3,
                   17,
                   19,
                   9,
                   7,
                   1,
                   3,
                   12,
                   16,
                   12,
                   1,
                   8,
                   5,
                   17,
                   2,
                   13,
                   18,
                   6,
                   17,
                   5,
                   9,
                   6,
                   19,
                   11,
                   10,
                   5,
                   18,
                   17,
                   8,
                   9,
                   10,
                   10,
                   6,
                   8,
                   4,
                   16,
                   12,
                   14,
                   3,
                   11,
                   9,
                   10,
                   14,
                   12,
                   2,
                   4,
                   2,
                   5,
                   5,
                   7,
                   3,
                   17,
                   11,
                   16,
                   16,
                   18,
                   6,
                   10,
                   18,
                   2,
                   2,
                   13,
                   17,
                   19,
                   3,
                   8,
                   14,
                   13,
                   14,
                   5,
                   9,
                   7,
                   5,
                   3,
                   6,
                   13,
                   11,
                   19,
                   5,
                   6,
                   2,
                   13,
                   7,
                   17,
                   12,
                   9,
                   6,
                   16,
                   9,
                   16,
                   14,
                   18,
                   14,
                   8,
                   19,
                   11,
                   8,
                   11,
                   7,
                   4,
                   10,
                   17,
                   8,
                   7,
                   5,
                   16,
                   17,
                   19,
                   13,
                   11,
                   15,
                   4,
                   13,
                   15,
                   7,
                   12,
                   13,
                   12,
                   12,
                   2,
                   18,
                   19,
                   11,
                   5,
                   11,
                   1,
                   8,
                   4,
                   2,
                   8,
                   15,
                   3,
                   7,
                   6,
                   4,
                   1,
                   17,
                   9,
                   17,
                   10,
                   5,
                   14,
                   9,
                   9,
                   8,
                   15,
                   4,
                   18,
                   13,
                   18,
                   8,
                   12,
                   8,
                   15,
                   10,
                   17,
                   12,
                   7,
                   13,
                   18,
                   18,
                   6,
                   19,
                   19,
                   15,
                   9,
                   7,
                   6,
                   7,
                   8,
                   16,
                   11,
                   3,
                   1,
                   12,
                   14,
                   2,
                   4,
                   6,
                   14,
                   1,
                   8,
                   3,
                   16,
                   17,
                   14,
                   16,
                   1,
                   9,
                   16,
                   3,
                   6,
                   10,
                   10,
                   15,
                   18,
                   13,
                   13,
                   5,
                   16,
                   11,
                   19,
                   9,
                   7,
                   3,
                   10,
                   7,
                   18,
                   19,
                   14,
                   3,
                   19,
                   6,
                   3,
                   2,
                   8,
                   14,
                   3,
                   11,
                   4,
                   7,
                   15,
                   17,
                   3,
                   11,
                   10,
                   12,
                   19,
                   15,
                   6,
                   14,
                   3,
                   19,
                   8,
                   5,
                   1,
                   9,
                   16,
                   13,
                   9,
                   2,
                   3,
                   16,
                   11,
                   14,
                   2,
                   17,
                   10,
                   19,
                   4,
                   2,
                   14,
                   1,
                   10,
                   1,
                   13,
                   19,
                   5,
                   15,
                   7,
                   3,
                   11,
                   4,
                   12,
                   3,
                   19,
                   4,
                   8,
                   13,
                   9,
                   1,
                   16,
                   10,
                   16,
                   12,
                   19,
                   14,
                   7,
                   17,
                   15,
                   18,
                   16,
                   4,
                   13,
                   9,
                   19,
                   13,
                   19,
                   12,
                   9,
                   9,
                   12,
                   10,
                   10,
                   9,
                   10,
                   7,
                   3,
                   17,
                   14,
                   18,
                   15,
                   10,
                   7,
                   10,
                   13,
                   8,
                   8,
                   10,
                   18,
                   15,
                   12,
                   16,
                   17,
                   16,
                   4,
                   19,
                   6,
                   15,
                   9,
                   15,
                   10,
                   13,
                   4,
                   14,
                   16,
                   9,
                   5,
                   3,
                   4,
                   16,
                   10,
                   6,
                   3,
                   16,
                   19,
                   5,
                   16,
                   7,
                   13,
                   8,
                   7,
                   19,
                   13,
                   11,
                   14,
                   4,
                   7,
                   18,
                   13,
                   6,
                   4,
                   10,
                   1,
                   8,
                   6,
                   12,
                   7,
                   5,
                   12,
                   18,
                   9,
                   5}; //Buradaki değer degisirse 17.satirdaki degeride degistirmek gereklidir.
    int sayac3 = 0;
    int asilDizi[BOYUT],yedekDizi[BOYUT];

    for(int i=0;i<BOYUT;i++)
    {
        asilDizi[i] = i+1;
    }

    for(int i=0;i<=1000;i++) //1000 yapacaksın burasını.
    {
        int deger1 = 1; //While için gereklidir.
        int deger2 = 0; //While için gereklidir.

        if(i % 100 == 0)
        {
            sayac3++;


            if(sayac3 == 1)
            {
                printf("\n\nBaşlangıç Dizisi\n\n");
                printf("%d.\t",sayac3);

                for(int k=0;k<BOYUT;k++)
                {
                    printf("%d - ",asilDizi[k]);
                }
                printf("\n\n\n");
                printf("Hesaplanan Diziler \n\n");
            }
            else
            {
                printf("%d.\t",sayac3);

                for(int k=0;k<BOYUT;k++)
                {
                    printf("%d - ",asilDizi[k]);
                }
                printf("\n");
            }
        }

        for(int j=0;j<dizi[i];j++)
        {
            yedekDizi[j] = asilDizi[j];
            asilDizi[j] = NULL;

        }
        for(int sayi=dizi[i];sayi<BOYUT;sayi++)
        {
            asilDizi[sayi-dizi[i]] = asilDizi[sayi];
            asilDizi[sayi] = 0;
        }
        while(1) {
            if (asilDizi[deger2] == 0) {
                asilDizi[deger2] = yedekDizi[dizi[i] - deger1];
                deger1++;
            }
            if(asilDizi[19] != 0)
            {
                break;
            }
            deger2++;
        }
        for(int sifirla=0;sifirla<BOYUT;sifirla++)
        {
            yedekDizi[sifirla] = NULL;
        }
    }
    for(int k=0;k<BOYUT;k++)
    {
        printf("%d\n",asilDizi[k]);
    }

    int cevap;
    printf("Menuye geri donmek istermisiniz \n (1-2)");
    scanf("%d",cevap);

    if(cevap == 1)
    {
        secimYap();
    }
    else if(cevap == 2)
    {
        main();
    }

}
int similasyonOyunu() {
    int sayac = 0;

    int hafiza1;
    int patatesSuresi = 0;
    srand(time(0));

    while (1)
    {
        int muzikSuresi = 10 + rand() %15 ;
        printf("\n----\nMuzik Suresi: %dsn\n----\n",muzikSuresi);

        for (int i=0; i<=muzikSuresi;)
        {
             patatesSuresi = 1 + rand() % 3;
            for (int j = 1; j <= adamSayisi; j++)
            {
                if (j == 1)
                {
                    hafiza1 = adamlar[0];
                }
                if (j > 0 && j < adamSayisi) {
                    adamlar[j - 1] = adamlar[j];
                }
            }
            adamlar[14] = hafiza1;


            patatesSuresi = 1 + rand() % 3;
            for (int k = 0; k < adamSayisi; k++) // Teker teker eleman yazdırır ekrana.
            {

                if(adamlar[k]  != 0)
                {
                    //sleep(patatesSuresi);

                    if(adamSayisi-sayac == 1)
                    {
                        if(adamlar[k] != 0)
                        {
                            printf("Kazanan: %d.oyuncu",adamlar[k]);
                        }
                        return  0;
                    }
                }
            }
            for(int b=0;b<adamSayisi-sayac;b++)
            {
                if(adamlar[b] != 0)
                {
                    if(adamlar[0] != 0)
                    {
                        i = i + patatesSuresi;
                        break;
                    }
                }
            }
            for(int b=0;b<adamSayisi;b++)
            {
                if(adamlar[b] != 0)
                {
                    if(adamlar[0] != 0)
                    {
                        printf("%d.oyuncu - ", adamlar[b]);

                        if(i > muzikSuresi)
                        {
                            sayac++;
                            //printf("\nElinde tuttugu sure: %d\n",patatesSuresi);
                            printf("\n----\nKaybeden oyuncu: %d\n----\n",adamlar[b]);
                            adamlar[b] = 0;
                            patatesSuresi = 0;
                            muzikSuresi = 0;
                            break;
                        }
                    }
                }
            }

            for(int c=0;c<adamSayisi;c++)
            {
                if(adamlar[c] != 0)
                {
                    if(adamlar[0] != 0)
                    {
                        printf("\nElinde tuttugu sure: %d\n",patatesSuresi);
                        break;
                    }
                }
            }
            sleep(patatesSuresi);
        }


    }

}
int main()
{
    int secim;

    printf("Secim Ekranina Hosgeldiniz \n");
    printf("1-) Sıralama\n");
    printf("2-) Simülasyon\n");
    printf("3-) Çıkış yap\n");
    printf("\nSecim yapınız: ");
    scanf("%d",&secim);
    switch (secim)
    {
        case 1:
            secimYap();
            break;

        case 2:
            similasyonOyunu();
            break;

        case 3:
            printf("Başarılı şekilde çıkış yapıldı.");
            exit(0);

        default:
            printf("\nLütfen şıklar arasından seçim yapınız.\n\n");
    }
}